### ISSUE TITLE
If last player leaves lobby it should be deleted and thus be unjoinable

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-server#114]

**Comment by pablotanner** [comment]
Implemented in:
https://github.com/sopra-fs23-group-13/meme-it-server/commit/87bac67b0216b67495b3d31d2abde75580803d89

Had small bug, fixed in:
https://github.com/sopra-fs23-group-13/meme-it-server/commit/4a71cddae042736e8f8814b007c8d9b0820b86f2
