### ISSUE TITLE
memes not saving in backend

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-server#125]
textBoxes are not stored correctly. the element is passed during the creation but it cannot be fetched.

**Comment by danielLutziger** [comment]
![image](https://user-images.githubusercontent.com/10813124/234039273-470c60ed-145a-46d0-bf79-091fd8f11113.png)

**Comment by danielLutziger** [comment]
![image](https://user-images.githubusercontent.com/10813124/234039504-1dd2bde5-daea-4dab-b8e8-27d54578a360.png)

**Comment by danielLutziger** [comment]
![image](https://user-images.githubusercontent.com/10813124/234039998-baf02218-1408-49cf-a041-c75a1d5d9f4d.png)

**Comment by Cnordg** [comment]
@danielLutziger It seems that problem lies with TextBox entity is not serialised properly

**Comment by Cnordg** [comment]
Setting `fetch = FetchType.EAGER` in the @OneToMany annotation does not solve the bug

**Comment by danielLutziger** [comment]
fixed.

**Comment by danielLutziger** [comment]
https://github.com/sopra-fs23-group-13/meme-it-server/pull/159
