### ISSUE TITLE
GameState gets stuck on "Voting" in last round 

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#162]
Correct state is given out in console but not on frontend/postman.

**Comment by danielLutziger** [comment]
GameJob.java line 101 has something to do with it.

**Comment by Cnordg** [comment]
I am not sure what you guys mean? The game_results phase is shown, so nothing is stuck
<img width="534" alt="Screenshot 2023-05-13 at 15 56 24" src="https://github.com/sopra-fs23-group-13/meme-it-server/assets/91025733/66f8c5a1-2137-4443-a820-6554b985fce4">
