### ISSUE TITLE
Game skips last voting round and goes straight to final leaderboard 

### ISSUE THREAD

**Issue by pablotanner** [sopra-fs23-group-13/meme-it-server#172]
Not sure if this is a frontend or backend issue, but game seems to skip the last round's voting phase either completely or after a couple of seconds before showing final leaderboard.

**Comment by danielLutziger** [comment]
quickly investigated it: backend bug

=> in the final round the following data is sent almost immediately: 
{... gameState : "GAME_RESULTS" ...}
