### ISSUE TITLE
persistance

### ISSUE THREAD

**Issue by danielLutziger** [sopra-fs23-group-13/meme-it-server#175]
we will need at least some persistance as mete mentioned that the h2 db will not be sufficient. To quickly store it this option would be feasible in app.properties:

spring.datasource.url=jdbc:h2:file:~/testdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

=> like that we would have some file storage. but the file gets deleted after a while as well when the server shuts down (google cloud)

**Comment by danielLutziger** [comment]
our app is not per se slow, but we have issues with google cloud.

spring.datasource.url=jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

=> this works if the db is shut down properly. if it is restarted and at the very same time there are requests from the fe to the backend it fucks up. 
![image](https://github.com/sopra-fs23-group-13/meme-it-server/assets/10813124/ec918a79-3488-4aa6-9665-8b0235d8cce6)

**Comment by danielLutziger** [comment]
i have tried to use a google cloud database and it did not work the way i wanted it to. thus i left this approach behind. but we need to clarify whether we now need a persistent storage or not as in a meeting mete mentioned something of it.

**Comment by Cnordg** [comment]
I definitely would not change the DB now this will def make us fail. What we could maybe change is increasing ram if we keep it in memory. In memory is the fastest solution so we might need to explore this. Can you clarify where the slow performance occurs? Is it the app start or during a game(s)?


On 20 May 2023, at 20:09, daniel ***@***.***> wrote:

﻿

i have tried to use a google cloud database and it did not work the way i wanted it to. thus i left this approach behind. but we need to clarify whether we now need a persistent storage or not as in a meeting mete mentioned something of it.
