### ISSUE TITLE
Increase test coverage to 75%

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-server#180]
I just want to note this issue here. @weberlii maybe we split it up between us?

**Comment by weberlii** [comment]
Yes, that sounds good. I was thinking to create classes EntityMother and DTOMother, to facilitate creating the example objects needed for testing. See this article I found https://martinfowler.com/bliki/ObjectMother.html

**Comment by weberlii** [comment]
Not sure how to test this (from the GameController) Meme meme = MemeMapper.INSTANCE.convertMemePostDTOtoEntity(memePostDTO); using an Mockito ArgumentCaptor maybe? I was thinking it might be worth it to refactor this and create a new class, unless you know how to properly test this the way it is now?

**Comment by weberlii** [comment]
GameControllerTest and GameServiceTest are refactored now and have additional tests, see 62de65a40062b74b4ad7a8a102d0735df9336a9a
