### ISSUE TITLE
Fix cold start issue on GCP

### ISSUE THREAD

**Issue by Cnordg** [sopra-fs23-group-13/meme-it-server#198]

**Comment by Cnordg** [comment]
[set-min-instance-to-1](https://github.com/sopra-fs23-group-13/meme-it-server/tree/set-min-instance-to-1) We need to first check our balance and pool them together before we merge that branch into main. @M-Schurr can you take over this?

**Comment by danielLutziger** [comment]
i have opened "/" for the frontend to call the application once started. To have at least a little faster start up but this does not fix the issue
